-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 10:34:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client_interne_gestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client_interne_gestion` (
  `idclient_interne_gestion` INT NOT NULL AUTO_INCREMENT,
  `client` VARCHAR(45) NULL,
  `interne` VARCHAR(45) NULL,
  `gestion` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient_interne_gestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vulnerabilities_nbr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vulnerabilities_nbr` (
  `idvulnerabilities_nbr` INT NOT NULL AUTO_INCREMENT,
  `medium_vulnerabilities` INT NULL,
  `high_vulnerabilities` INT NULL,
  `critical_vulnerabilities` INT NULL,
  PRIMARY KEY (`idvulnerabilities_nbr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ip1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ip1` (
  `idip1` INT NOT NULL AUTO_INCREMENT,
  `ip1_content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idip1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ip2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ip2` (
  `idip2` INT NOT NULL AUTO_INCREMENT,
  `ip2_content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idip2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ip3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ip3` (
  `idip3` INT NOT NULL AUTO_INCREMENT,
  `ip3_content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idip3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ip4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ip4` (
  `idip4` INT NOT NULL AUTO_INCREMENT,
  `ip4_content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idip4`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`iptype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`iptype` (
  `idiptype` INT NOT NULL AUTO_INCREMENT,
  `ipv4` INT NULL,
  `ipv6` INT NULL,
  PRIMARY KEY (`idiptype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acceptation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acceptation` (
  `idacceptation` INT NOT NULL AUTO_INCREMENT,
  `acceptation_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idacceptation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesures_att_rem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesures_att_rem` (
  `idmesures_att_rem` INT NOT NULL AUTO_INCREMENT,
  `mesures_att_rem_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmesures_att_rem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recommandations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recommandations` (
  `idrecommandations` INT NOT NULL AUTO_INCREMENT,
  `recommandations_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecommandations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`risk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`risk` (
  `idrisk` INT NOT NULL AUTO_INCREMENT,
  `risk_description` VARCHAR(45) NOT NULL,
  `acceptation_idacceptation` INT NOT NULL,
  `mesures_att_rem_idmesures_att_rem` INT NOT NULL,
  `recommandations_idrecommandations` INT NOT NULL,
  PRIMARY KEY (`idrisk`),
  INDEX `fk_risk_acceptation1_idx` (`acceptation_idacceptation` ASC) ,
  INDEX `fk_risk_mesures_att_rem1_idx` (`mesures_att_rem_idmesures_att_rem` ASC) ,
  INDEX `fk_risk_recommandations1_idx` (`recommandations_idrecommandations` ASC) ,
  CONSTRAINT `fk_risk_acceptation1`
    FOREIGN KEY (`acceptation_idacceptation`)
    REFERENCES `mydb`.`acceptation` (`idacceptation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_risk_mesures_att_rem1`
    FOREIGN KEY (`mesures_att_rem_idmesures_att_rem`)
    REFERENCES `mydb`.`mesures_att_rem` (`idmesures_att_rem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_risk_recommandations1`
    FOREIGN KEY (`recommandations_idrecommandations`)
    REFERENCES `mydb`.`recommandations` (`idrecommandations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ip` (
  `idip` INT NOT NULL AUTO_INCREMENT,
  `ip1_idip1` INT NOT NULL,
  `ip2_idip2` INT NOT NULL,
  `iptype_idiptype` INT NOT NULL,
  `ip3_idip3` INT NOT NULL,
  `ip4_idip4` INT NOT NULL,
  `client_interne_gestion_idclient_interne_gestion` INT NOT NULL,
  `vulnerabilities_nbr_idvulnerabilities_nbr` INT NOT NULL,
  `risk_idrisk` INT NOT NULL,
  `risk_recommandations_idrecommandations` INT NOT NULL,
  PRIMARY KEY (`idip`),
  INDEX `fk_ip_ip11_idx` (`ip1_idip1` ASC) ,
  INDEX `fk_ip_ip21_idx` (`ip2_idip2` ASC) ,
  INDEX `fk_ip_iptype1_idx` (`iptype_idiptype` ASC) ,
  INDEX `fk_ip_ip31_idx` (`ip3_idip3` ASC) ,
  INDEX `fk_ip_ip41_idx` (`ip4_idip4` ASC) ,
  INDEX `fk_ip_client_interne_gestion1_idx` (`client_interne_gestion_idclient_interne_gestion` ASC) ,
  INDEX `fk_ip_vulnerabilities_nbr1_idx` (`vulnerabilities_nbr_idvulnerabilities_nbr` ASC) ,
  INDEX `fk_ip_risk1_idx` (`risk_idrisk` ASC, `risk_recommandations_idrecommandations` ASC) ,
  CONSTRAINT `fk_ip_ip11`
    FOREIGN KEY (`ip1_idip1`)
    REFERENCES `mydb`.`ip1` (`idip1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_ip21`
    FOREIGN KEY (`ip2_idip2`)
    REFERENCES `mydb`.`ip2` (`idip2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_iptype1`
    FOREIGN KEY (`iptype_idiptype`)
    REFERENCES `mydb`.`iptype` (`idiptype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_ip31`
    FOREIGN KEY (`ip3_idip3`)
    REFERENCES `mydb`.`ip3` (`idip3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_ip41`
    FOREIGN KEY (`ip4_idip4`)
    REFERENCES `mydb`.`ip4` (`idip4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_client_interne_gestion1`
    FOREIGN KEY (`client_interne_gestion_idclient_interne_gestion`)
    REFERENCES `mydb`.`client_interne_gestion` (`idclient_interne_gestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_vulnerabilities_nbr1`
    FOREIGN KEY (`vulnerabilities_nbr_idvulnerabilities_nbr`)
    REFERENCES `mydb`.`vulnerabilities_nbr` (`idvulnerabilities_nbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_risk1`
    FOREIGN KEY (`risk_idrisk`)
    REFERENCES `mydb`.`risk` (`idrisk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
